language: ruby

rvm:
  - 2.3

services:
  - docker

env:
  - TERRAFORM_VERSION=latest MODULE_NAME=terraform-azurerm-sql

jobs:
  include:
    - stage: build
      if: type = pull_request
      install: true
      script:
        - docker build --build-arg BUILD_TERRAFORM_VERSION=${TERRAFORM_VERSION} -t ${MODULE_NAME} .
        - docker run ${MODULE_NAME} rake build
    - stage: full
      if: type = push AND branch = master
      install: true
      script:
        - docker build --build-arg BUILD_TERRAFORM_VERSION=${TERRAFORM_VERSION} --build-arg BUILD_ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID --build-arg BUILD_ARM_CLIENT_ID=$ARM_CLIENT_ID --build-arg BUILD_ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET --build-arg BUILD_ARM_TENANT_ID=$ARM_TENANT_ID -t ${MODULE_NAME} .
        - docker run ${MODULE_NAME} /bin/bash -c "bundle install && rake e2e"